---

- name: create group
  group: name={{ cuckoo_group }}
  sudo: yes

- name: create user
  user: name={{ cuckoo_user }} group={{ cuckoo_group }}
  sudo: yes

- name: create application directory (owned by ansible ssh user)
  file: path={{ cuckoo_deploy_to }} state=directory owner={{ ansible_ssh_user }} group={{ ansible_ssh_user }}
  sudo: yes

- name: install git
  sudo: yes
  apt: pkg=git update_cache=yes

- name: check if known_hosts exists
  stat: path=~{{ ansible_ssh_user }}/.ssh/known_hosts
  register: known_hosts_file
  when: cuckoo_pull_from_git == True

- name: ensure github.com in known host
  shell: ssh-keyscan -H github.com >> ~{{ ansible_ssh_user }}/.ssh/known_hosts
  when: cuckoo_pull_from_git == True and known_hosts_file.stat.exists == false

- name: clone repo to application directory
  git: dest={{ cuckoo_deploy_to }} repo={{ cuckoo_repo }} version=master
  when: cuckoo_pull_from_git == True

- name: make application directory be owned by application user
  file: path={{ cuckoo_deploy_to }} state=directory recurse=yes owner={{ cuckoo_user }}
  sudo: yes
